from __future__ import annotations

from flask import Blueprint, current_app, render_template, send_from_directory

from app.images import image_directory, is_generated_image_filename

bp = Blueprint("pages", __name__)


@bp.get("/")
def home():
    return render_template("home.html")


@bp.get("/images/<filename>")
def image(filename: str):
    # These names are generated by the application. Checking before delegating
    # to Flask's safe directory join keeps this intentionally public route
    # unable to expose any other persistent-data file.
    if not is_generated_image_filename(filename):
        return render_template("errors/not_found.html"), 404
    data_dir = current_app.config["APP_CONFIG"].data_dir
    return send_from_directory(
        image_directory(data_dir), filename, mimetype="image/webp"
    )
